---

# cfn-lint -t devuser.yaml  
# aws s3 sync s3://devproject-cf-templates .

AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  Development environment template for developers to join to a development project.

Parameters:
  Env:
    Description: "Please specify the target env. (Used for tagging and resource names)"
    Type: "String"
    Default: "poc"
    AllowedValues:
      - "poc"
      - "dev"
      - "prod"

  ProjectName:
    Description: "Name of the project."
    Type: "String"
    Default: "sample-project"

  EC2InstanceType:
    Description: "EC2 instance type on which the IDE runs"
    Type: "String"
    Default: "t2.micro"
    AllowedValues:
      - "t2.micro"
      - "t2.small"
      - "t2.medium"

  AutoHibernateTimeout:
    Description: "Idle minutes before IDE shutdown. Options, 30min, 1hr, 4hr, 1day, 1week, Never (0)"
    Type: "Number"
    Default: 30
    AllowedValues:
      - 30
      - 60
      - 240
      - 1440
      - 10080
      - 0

  User:
    Description: "User name."
    Type: "String"
    Default: "test"

Resources:

  UserToGroupAdd:
    Type: AWS::IAM::UserToGroupAddition
    Properties: 
      GroupName: 
        Fn::ImportValue: !Sub "${ProjectName}-iam-group-cloud9-user" 
      Users: 
        - !Sub "${User}"

  C9IDE:
    Type: 'AWS::Cloud9::EnvironmentEC2'
    Properties:
      Name: !Sub '${User}-${Env}-Cloud9-IDE'
      Description: !Sub '${User} Cloud9 IDE'
      AutomaticStopTimeMinutes: !Ref 'AutoHibernateTimeout'
      SubnetId: 
        Fn::ImportValue: !Sub '${ProjectName}-ide-subnet'
      InstanceType: !Ref 'EC2InstanceType'
      ImageId: 'ami-07a458d01f2e60e3f'
      Repositories:
          - RepositoryUrl: 
              Fn::ImportValue: !Sub '${ProjectName}-infrastructure-repository-url'
            PathComponent: !Sub 'codecommit/${AWS::StackName}-infrastructure-repository'
      Tags:
        - Key: "project"
          Value: !Ref 'ProjectName'
    DependsOn:
      - UserToGroupAdd

Outputs:
  Cloud9URL:
    Description: Cloud9 Environment
    Value:
      Fn::Join:
        - ""
        - - !Sub https://${AWS::Region}.console.aws.amazon.com/cloud9/ide/
          - !Ref "C9IDE"
